Dev1
kamar19/TraineeMoveApp pull request #4
Opened 2023-02-25 14:29 UTC by kamar19

Задача 2.1

2023-02-26 16:55 UTC, ermolnik requested changes

2023-02-26 16:55 UTC, ermolnik commented on app/src/main/java/com/example/traineemoveapp/compose/filmDetails/ActorListItem.kt
> +            .clip(RoundedCornerShape(5)))
Вот тут dp не должно быть?

2023-02-26 16:55 UTC, ermolnik commented on app/src/main/java/com/example/traineemoveapp/compose/filmDetails/FilmDetailsFragment.kt
> +                        ActorsListView(viewModel, film.actor_ids)
Вот тут у тебя прокидывается просто список вместо Стейта, если тебе нужно будет пробрасывать какие-то изменения этого списка, скорее всего композабл их не станет обрабатывать

2023-02-26 16:55 UTC, ermolnik commented on app/src/main/java/com/example/traineemoveapp/compose/filmList/FilmListFragment.kt
> +                text.value = it
Вот тут у тебя результат ввода не пробрасывается во viewmodel, он должен обрабатываться там

2023-02-26 16:55 UTC, ermolnik commented on app/src/main/java/com/example/traineemoveapp/compose/filmList/FilmListFragment.kt
> +        val onClickToSelectCategory2: () -> Unit = {
Выглядит как костыль

2023-02-26 16:55 UTC, ermolnik commented on app/src/main/java/com/example/traineemoveapp/model/Actor.kt
> +data class Actor (var id: Int? = null,
Может ли у актера не быть id или имени? В чем смысл такой сущности?

2023-02-26 16:55 UTC, ermolnik commented on app/src/main/java/com/example/traineemoveapp/model/Film.kt
> +        var pg: String = "",
Что такое pg

2023-02-26 16:55 UTC, ermolnik commented on app/src/main/java/com/example/traineemoveapp/repository/FromJsonRepository.kt
> +    val stream = context.assets.open(MainActivity.ASSET_FILE_NAME)
Что такое stream и stream2

2023-02-26 16:55 UTC, ermolnik commented on app/src/main/java/com/example/traineemoveapp/viewModel/DetailFilmViewModel.kt
> +            4-> return R.drawable.act4
Код не отформатирован

2023-02-28 12:11 UTC, kamar19 commented on app/src/main/java/com/example/traineemoveapp/compose/filmDetails/ActorListItem.kt
> +            .clip(RoundedCornerShape(5)))
Удалил размеры. Если правильно понял размеры должны браться из размеров картинок? А если они разные придут.

2023-02-28 13:41 UTC, kamar19 commented on app/src/main/java/com/example/traineemoveapp/compose/filmList/FilmListFragment.kt
> +                text.value = it
результат ввода пробрасывается во viewmode через ниже расположенный вызов  - onInputText(text.value).    
Переделал, твой совет лучше. Убрал этот колбек, и выполняю вызов из этого места.

2023-02-28 13:53 UTC, kamar19 commented on app/src/main/java/com/example/traineemoveapp/compose/filmList/FilmListFragment.kt
> +        val onClickToSelectCategory2: () -> Unit = {
При чем костыль который ни чего не делает. Что то напутал тут.

2023-02-28 14:06 UTC, kamar19 commented on app/src/main/java/com/example/traineemoveapp/model/Actor.kt
> +data class Actor (var id: Int? = null,
исправил

2023-02-28 14:08 UTC, kamar19 commented on app/src/main/java/com/example/traineemoveapp/model/Film.kt
> +        var pg: String = "",
это Parental Guidance - рейтинг фильмов по возврасту

2023-02-28 14:10 UTC, kamar19 commented on app/src/main/java/com/example/traineemoveapp/repository/FromJsonRepository.kt
> +    val stream = context.assets.open(MainActivity.ASSET_FILE_NAME)
stream и stream2 это временные переменные InputStream для открытия конкретных, нужных файлов.

2023-02-28 14:11 UTC, kamar19 commented on app/src/main/java/com/example/traineemoveapp/viewModel/DetailFilmViewModel.kt
> +            4-> return R.drawable.act4
выполнил

2023-02-28 14:40 UTC, kamar19 commented on app/src/main/java/com/example/traineemoveapp/compose/filmDetails/FilmDetailsFragment.kt
> +                        ActorsListView(viewModel, film.actor_ids)
исправил

2023-03-01 15:56 UTC, ermolnik requested changes

2023-03-01 15:56 UTC, ermolnik commented on app/src/main/java/com/example/traineemoveapp/compose/filmDetails/FilmDetailsFragment.kt
> +    val film = viewModel.uiState.value.film
У тебя вот тут должен быть collectAsState скорее всего 
Без него изменения в списке не будут обрабатываться compose

2023-03-07 17:26 UTC, merged